//
// Created by Aubrey on 3/30/2024.
//

#ifndef NIFTYDSC_GUICONSTANTS_HPP
#define NIFTYDSC_GUICONSTANTS_HPP

#define GUI_BACKGROUND 0x0000
#define GUI_DEFAULT 0xF800
#define GUI_SELECT 0xF900
#define GUI_DIMMED 0xA000

#endif  // NIFTYDSC_GUICONSTANTS_HPP